name: build recipes
on:
  push:
    branches:
      - 'add_new_layer'
  pull_request:
  workflow_dispatch:

jobs:

  build_recipes:
    runs-on: ubuntu-latest
    env:
      TARGET_PLATFORM: emscripten-32
      #GITHUB_OWNER: "emscripten-forge"
      GITHUB_OWNER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHANNEL: "conda-bld"
    strategy:
      fail-fast: false
      matrix:
        emsdk_ver: ["3.1.2"]
        subdir: [emscripten-32,linux-64,noarch]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}


      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      ################################################################
      # timestamp
      ################################################################
      - name: generate cache timestamp
        id: cache_timestamp
        shell: bash -l {0}
        run: echo ::set-output name=timestamp::"$(TZ=UTC date +%F)"

      ################################################################
      # CONFIG
      ################################################################
      - name: global config
        shell: bash -l {0}
        run: |
          git config --global advice.detachedHead false
          cp $GITHUB_WORKSPACE/.github/workflows/.condarc $HOME
          cp $GITHUB_WORKSPACE/conda_build_config.yaml $HOME

      ################################################################
      # MAMBA
      ################################################################
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci_env.yml
          environment-name: ci-env
          micromamba-version: '0.23.2'

      ################################################################
      # POST ENV INSTALL CONFIG
      ################################################################
      - name: post env install config
        shell: bash -l {0}
        run: |
          mkdir -p $HOME/micromamba/envs/ci-env/conda-bld/emscripten-32
          mkdir -p $HOME/packed

          cp $GITHUB_WORKSPACE/.github/workflows/.condarc_post $HOME/.condarc
          micromamba activate ci-env
          playwright install


      ################################################################
      # Setup emsdk
      ################################################################
      - name: install emsdk
        shell: bash -l {0}
        run: |
          micromamba activate ci-env
          emsdk install ${{matrix.emsdk_ver}}

      ################################################################
      # install / clone custom non-master things
      # for pip, we use --no-deps --ignore-installed
      # and make sure that all dependencies are already contained
      # in the conda env named "ci-env"
      ################################################################
      - name: "install custom non-master dependencies"
        shell: bash -l {0}
        run: |
          micromamba activate ci-env
          python -m pip install git+https://github.com/DerThorsten/boa.git@postcb                --no-deps --ignore-installed
          python -m pip install git+https://github.com/DerThorsten/bitfurnace.git@emscripten_new --no-deps --ignore-installed


      ################################################################
      # build recipes with changes PUSH
      ################################################################
      - name: "build packages push"
        shell: bash -l {0}
        if: github.event_name == 'push'
        run: |
          micromamba activate ci-env
          cd ${GITHUB_WORKSPACE}
          emsdk activate ${{matrix.emsdk_ver}}
          source $CONDA_EMSDK_DIR/emsdk_env.sh
          python builder.py build changed $GITHUB_WORKSPACE/recipes origin/main~1 origin/main ~/webenv ~/packed

      ################################################################
      # build ALL recipes
      ################################################################
      - name: "build packages workflow_dispatch"
        shell: bash -l {0}
        if: github.event_name == 'workflow_dispatch'
        run: |
          micromamba activate ci-env
          cd ${GITHUB_WORKSPACE}
          emsdk activate ${{matrix.emsdk_ver}}
          source $CONDA_EMSDK_DIR/emsdk_env.sh

          python builder.py build directory  $GITHUB_WORKSPACE/recipes/recipes             /home/runner/webenv /home/runner/packed --skip-tests --skip-pack
          python builder.py build directory  $GITHUB_WORKSPACE/recipes/recipes_emscripten  /home/runner/webenv /home/runner/packed --emscripten-32


      ################################################################
      # build recipes with changes PULL_REQUEST
      ################################################################
      - name: "build packages pull_request"
        shell: bash -l {0}
        if: github.event_name == 'pull_request'
        run: |
          micromamba activate ci-env
          cd ${GITHUB_WORKSPACE}
          emsdk activate ${{matrix.emsdk_ver}}
          source $CONDA_EMSDK_DIR/emsdk_env.sh
          python builder.py build changed  $GITHUB_WORKSPACE/recipes origin/main HEAD  /home/runner/webenv /home/runner/packed


      ################################################################
      # github upload emscripten packed pkgs
      ################################################################
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push'
        with:
          name: emscripten_packed_pkgs
          path: ~/packed/* # or path/to/artifact\

      ################################################################
      # github upload emscripten packed pkgs
      ################################################################
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          name: emscripten_packed_pkgs
          path: ~/packed/* # or path/to/artifact\


      ################################################################
      # quetz upload packages
      ################################################################
      - name:  upload packages to githubO CI
        run: |
          python -m pip install git+https://github.com/mamba-org/conda_oci_mirror@main
          echo ${{ env.GITHUB_TOKEN }} | oras login https://ghcr.io -u ${{ env.GITHUB_OWNER }} --password-stdin
          python upload_packges.py ${{ env.GITHUB_OWNER }} ${CONDA_PREFIX} ${{ env.CHANNEL }} ${{ matrix.subdir }}
        shell: bash -l {0}
